### ISSUE TITLE
供POSTMAN使用的hanlp-api.postman_collection文件无法下载

### ISSUE THREAD

**Issue by fishfree** [Samurais/node-hanlp#1]
我下载运行了 https://hub.docker.com/r/samurais/hanlp-api/ 。 docker的web页面打开后提示要下载hanlp-api.postman_collection，点开链接后是502错误，翻墙后还是照旧。可否把这个文件发发出来？多谢！

**Comment by hailiang-wang** [comment]
hanlp-api.postman_collection可以使用这样的方式下载：
```
docker run -it --rm -p 3002:3000 samurais/hanlp-api:1.0.0
wget http://localhost:3002/public/hanlp-api.postman_collection
```

**Comment by fishfree** [comment]
可以下载了，谢谢！原来就是示例的导出文件。没有它也完全可以用POSTMAN自己搞啊
